<?php
/**
 * KidsAgeBand
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * KidsAgeBand Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KidsAgeBand
{
    /**
     * Possible values of this enum
     */
    const FIVE_AND_UNDER = 'FIVE_AND_UNDER';
    const SIX_TO_EIGHT = 'SIX_TO_EIGHT';
    const NINE_TO_ELEVEN = 'NINE_TO_ELEVEN';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FIVE_AND_UNDER,
            self::SIX_TO_EIGHT,
            self::NINE_TO_ELEVEN,
        ];
    }
}


