<?php
/**
 * ScreenshotDisplayType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ScreenshotDisplayType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScreenshotDisplayType
{
    /**
     * Possible values of this enum
     */
    const APP_IPHONE_65 = 'APP_IPHONE_65';
    const APP_IPHONE_58 = 'APP_IPHONE_58';
    const APP_IPHONE_55 = 'APP_IPHONE_55';
    const APP_IPHONE_47 = 'APP_IPHONE_47';
    const APP_IPHONE_40 = 'APP_IPHONE_40';
    const APP_IPHONE_35 = 'APP_IPHONE_35';
    const APP_IPAD_PRO_3_GEN_129 = 'APP_IPAD_PRO_3GEN_129';
    const APP_IPAD_PRO_3_GEN_11 = 'APP_IPAD_PRO_3GEN_11';
    const APP_IPAD_PRO_129 = 'APP_IPAD_PRO_129';
    const APP_IPAD_105 = 'APP_IPAD_105';
    const APP_IPAD_97 = 'APP_IPAD_97';
    const APP_DESKTOP = 'APP_DESKTOP';
    const APP_WATCH_SERIES_4 = 'APP_WATCH_SERIES_4';
    const APP_WATCH_SERIES_3 = 'APP_WATCH_SERIES_3';
    const APP_APPLE_TV = 'APP_APPLE_TV';
    const IMESSAGE_APP_IPHONE_65 = 'IMESSAGE_APP_IPHONE_65';
    const IMESSAGE_APP_IPHONE_58 = 'IMESSAGE_APP_IPHONE_58';
    const IMESSAGE_APP_IPHONE_55 = 'IMESSAGE_APP_IPHONE_55';
    const IMESSAGE_APP_IPHONE_47 = 'IMESSAGE_APP_IPHONE_47';
    const IMESSAGE_APP_IPHONE_40 = 'IMESSAGE_APP_IPHONE_40';
    const IMESSAGE_APP_IPAD_PRO_3_GEN_129 = 'IMESSAGE_APP_IPAD_PRO_3GEN_129';
    const IMESSAGE_APP_IPAD_PRO_3_GEN_11 = 'IMESSAGE_APP_IPAD_PRO_3GEN_11';
    const IMESSAGE_APP_IPAD_PRO_129 = 'IMESSAGE_APP_IPAD_PRO_129';
    const IMESSAGE_APP_IPAD_105 = 'IMESSAGE_APP_IPAD_105';
    const IMESSAGE_APP_IPAD_97 = 'IMESSAGE_APP_IPAD_97';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APP_IPHONE_65,
            self::APP_IPHONE_58,
            self::APP_IPHONE_55,
            self::APP_IPHONE_47,
            self::APP_IPHONE_40,
            self::APP_IPHONE_35,
            self::APP_IPAD_PRO_3_GEN_129,
            self::APP_IPAD_PRO_3_GEN_11,
            self::APP_IPAD_PRO_129,
            self::APP_IPAD_105,
            self::APP_IPAD_97,
            self::APP_DESKTOP,
            self::APP_WATCH_SERIES_4,
            self::APP_WATCH_SERIES_3,
            self::APP_APPLE_TV,
            self::IMESSAGE_APP_IPHONE_65,
            self::IMESSAGE_APP_IPHONE_58,
            self::IMESSAGE_APP_IPHONE_55,
            self::IMESSAGE_APP_IPHONE_47,
            self::IMESSAGE_APP_IPHONE_40,
            self::IMESSAGE_APP_IPAD_PRO_3_GEN_129,
            self::IMESSAGE_APP_IPAD_PRO_3_GEN_11,
            self::IMESSAGE_APP_IPAD_PRO_129,
            self::IMESSAGE_APP_IPAD_105,
            self::IMESSAGE_APP_IPAD_97,
        ];
    }
}


