<?php
/**
 * AppEncryptionDeclarationAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * AppEncryptionDeclarationAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description AppEncryptionDeclarationAttributes
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AppEncryptionDeclarationAttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppEncryptionDeclarationAttributes"
     */
    public function testAppEncryptionDeclarationAttributes()
    {
    }

    /**
     * Test attribute "uses_encryption"
     */
    public function testPropertyUsesEncryption()
    {
    }

    /**
     * Test attribute "exempt"
     */
    public function testPropertyExempt()
    {
    }

    /**
     * Test attribute "contains_proprietary_cryptography"
     */
    public function testPropertyContainsProprietaryCryptography()
    {
    }

    /**
     * Test attribute "contains_third_party_cryptography"
     */
    public function testPropertyContainsThirdPartyCryptography()
    {
    }

    /**
     * Test attribute "available_on_french_store"
     */
    public function testPropertyAvailableOnFrenchStore()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "uploaded_date"
     */
    public function testPropertyUploadedDate()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }

    /**
     * Test attribute "document_name"
     */
    public function testPropertyDocumentName()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "app_encryption_declaration_state"
     */
    public function testPropertyAppEncryptionDeclarationState()
    {
    }

    /**
     * Test attribute "code_value"
     */
    public function testPropertyCodeValue()
    {
    }
}
