<?php
/**
 * AppStoreVersionUpdateRequestDataAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * AppStoreVersionUpdateRequestDataAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description AppStoreVersionUpdateRequestDataAttributes
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AppStoreVersionUpdateRequestDataAttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppStoreVersionUpdateRequestDataAttributes"
     */
    public function testAppStoreVersionUpdateRequestDataAttributes()
    {
    }

    /**
     * Test attribute "version_string"
     */
    public function testPropertyVersionString()
    {
    }

    /**
     * Test attribute "copyright"
     */
    public function testPropertyCopyright()
    {
    }

    /**
     * Test attribute "release_type"
     */
    public function testPropertyReleaseType()
    {
    }

    /**
     * Test attribute "earliest_release_date"
     */
    public function testPropertyEarliestReleaseDate()
    {
    }

    /**
     * Test attribute "uses_idfa"
     */
    public function testPropertyUsesIdfa()
    {
    }

    /**
     * Test attribute "downloadable"
     */
    public function testPropertyDownloadable()
    {
    }
}
