<?php
/**
 * AppStoreReviewDetailAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * AppStoreReviewDetailAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description AppStoreReviewDetailAttributes
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AppStoreReviewDetailAttributesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppStoreReviewDetailAttributes"
     */
    public function testAppStoreReviewDetailAttributes()
    {
    }

    /**
     * Test attribute "contact_first_name"
     */
    public function testPropertyContactFirstName()
    {
    }

    /**
     * Test attribute "contact_last_name"
     */
    public function testPropertyContactLastName()
    {
    }

    /**
     * Test attribute "contact_phone"
     */
    public function testPropertyContactPhone()
    {
    }

    /**
     * Test attribute "contact_email"
     */
    public function testPropertyContactEmail()
    {
    }

    /**
     * Test attribute "demo_account_name"
     */
    public function testPropertyDemoAccountName()
    {
    }

    /**
     * Test attribute "demo_account_password"
     */
    public function testPropertyDemoAccountPassword()
    {
    }

    /**
     * Test attribute "demo_account_required"
     */
    public function testPropertyDemoAccountRequired()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }
}
