<?php
/**
 * BundleIdsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BundleIdsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BundleIdsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bundleIdsAppGetToOneRelated
     *
     * .
     *
     */
    public function testBundleIdsAppGetToOneRelated()
    {
    }

    /**
     * Test case for bundleIdsBundleIdCapabilitiesGetToManyRelated
     *
     * .
     *
     */
    public function testBundleIdsBundleIdCapabilitiesGetToManyRelated()
    {
    }

    /**
     * Test case for bundleIdsCreateInstance
     *
     * .
     *
     */
    public function testBundleIdsCreateInstance()
    {
    }

    /**
     * Test case for bundleIdsDeleteInstance
     *
     * .
     *
     */
    public function testBundleIdsDeleteInstance()
    {
    }

    /**
     * Test case for bundleIdsGetCollection
     *
     * .
     *
     */
    public function testBundleIdsGetCollection()
    {
    }

    /**
     * Test case for bundleIdsGetInstance
     *
     * .
     *
     */
    public function testBundleIdsGetInstance()
    {
    }

    /**
     * Test case for bundleIdsProfilesGetToManyRelated
     *
     * .
     *
     */
    public function testBundleIdsProfilesGetToManyRelated()
    {
    }

    /**
     * Test case for bundleIdsUpdateInstance
     *
     * .
     *
     */
    public function testBundleIdsUpdateInstance()
    {
    }
}
