<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * App Store Connect API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for usersDeleteInstance
     *
     * .
     *
     */
    public function testUsersDeleteInstance()
    {
    }

    /**
     * Test case for usersGetCollection
     *
     * .
     *
     */
    public function testUsersGetCollection()
    {
    }

    /**
     * Test case for usersGetInstance
     *
     * .
     *
     */
    public function testUsersGetInstance()
    {
    }

    /**
     * Test case for usersUpdateInstance
     *
     * .
     *
     */
    public function testUsersUpdateInstance()
    {
    }

    /**
     * Test case for usersVisibleAppsCreateToManyRelationship
     *
     * .
     *
     */
    public function testUsersVisibleAppsCreateToManyRelationship()
    {
    }

    /**
     * Test case for usersVisibleAppsDeleteToManyRelationship
     *
     * .
     *
     */
    public function testUsersVisibleAppsDeleteToManyRelationship()
    {
    }

    /**
     * Test case for usersVisibleAppsGetToManyRelated
     *
     * .
     *
     */
    public function testUsersVisibleAppsGetToManyRelated()
    {
    }

    /**
     * Test case for usersVisibleAppsGetToManyRelationship
     *
     * .
     *
     */
    public function testUsersVisibleAppsGetToManyRelationship()
    {
    }

    /**
     * Test case for usersVisibleAppsReplaceToManyRelationship
     *
     * .
     *
     */
    public function testUsersVisibleAppsReplaceToManyRelationship()
    {
    }
}
